spring.application.name=minisoc

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/minisoc_logs
spring.datasource.username=soc_user
spring.datasource.password=mini_soc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect